"""init

Revision ID: 07110bc84f97
Revises:
Create Date: 2020-06-17 19:21:51.926914

"""

# revision identifiers, used by Alembic.
revision = "07110bc84f97"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
