"""Rename uid to chat_id

Revision ID: 2dd07a4ac568
Revises: 512a2a041838
Create Date: 2020-06-15 20:14:23.279561

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2dd07a4ac568"
down_revision = "512a2a041838"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("chat_id", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("first_name", sa.String(length=100), nullable=True))
    op.add_column("user", sa.Column("last_name", sa.String(length=100), nullable=True))
    op.drop_column("user", "full_name")
    op.drop_column("user", "uid")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("uid", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user",
        sa.Column(
            "full_name", sa.VARCHAR(length=30), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("user", "last_name")
    op.drop_column("user", "first_name")
    op.drop_column("user", "chat_id")
    # ### end Alembic commands ###
