"""Init db

Revision ID: 512a2a041838
Revises: 
Create Date: 2020-06-03 21:51:50.887241

"""

# revision identifiers, used by Alembic.
revision = '512a2a041838'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
