"""add user.locale

Revision ID: 5138225aa09a
Revises: 2dd07a4ac568
Create Date: 2020-06-15 20:37:08.707938

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5138225aa09a"
down_revision = "2dd07a4ac568"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("locale", sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "locale")
    # ### end Alembic commands ###
