"""Init

Revision ID: 74a18c7c141e
Revises: 
Create Date: 2020-06-02 20:39:39.342416

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '74a18c7c141e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'limit')
    op.drop_column('card', 'status')
    # ### end Alembic commands ###
