"""item tables

Revision ID: 01937bb403bd
Revises: 46c76a9be90c
Create Date: 2020-07-02 14:09:40.331825

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "01937bb403bd"
down_revision = "46c76a9be90c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "item_options",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("calculated_price", sa.Float(), nullable=True),
        sa.Column(
            "condition",
            sa.Enum("near_mint", "played", "heavily_played", name="itemcondition"),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_item_options_id"), "item_options", ["id"], unique=True)
    op.create_table(
        "localized_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("item_name", sa.String(), nullable=True),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_localized_items_id"), "localized_items", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_localized_items_item_name"),
        "localized_items",
        ["item_name"],
        unique=False,
    )
    op.add_column("items", sa.Column("card_type", sa.String(), nullable=True))
    op.add_column("items", sa.Column("finish", sa.String(), nullable=True))
    op.add_column("items", sa.Column("original_name", sa.String(), nullable=True))
    op.add_column("items", sa.Column("product_id", sa.Integer(), nullable=True))
    op.add_column("items", sa.Column("rarity", sa.String(), nullable=True))
    op.add_column("items", sa.Column("set_name", sa.String(), nullable=True))
    op.add_column("items", sa.Column("source", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_items_original_name"), "items", ["original_name"], unique=False
    )
    op.create_index(op.f("ix_items_product_id"), "items", ["product_id"], unique=False)
    op.create_index(op.f("ix_items_set_name"), "items", ["set_name"], unique=False)
    op.drop_column("items", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_items_set_name"), table_name="items")
    op.drop_index(op.f("ix_items_product_id"), table_name="items")
    op.drop_index(op.f("ix_items_original_name"), table_name="items")
    op.drop_column("items", "source")
    op.drop_column("items", "set_name")
    op.drop_column("items", "rarity")
    op.drop_column("items", "product_id")
    op.drop_column("items", "original_name")
    op.drop_column("items", "finish")
    op.drop_column("items", "card_type")
    op.drop_index(op.f("ix_localized_items_item_name"), table_name="localized_items")
    op.drop_index(op.f("ix_localized_items_id"), table_name="localized_items")
    op.drop_table("localized_items")
    op.drop_index(op.f("ix_item_options_id"), table_name="item_options")
    op.drop_table("item_options")
    sa.Enum(name="itemcondition").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
