"""remove_item.user_id

Revision ID: 46c76a9be90c
Revises: 327cb2b9bb41
Create Date: 2020-06-22 15:55:58.334601

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "46c76a9be90c"
down_revision = "327cb2b9bb41"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("items_user_id_fkey", "items", type_="foreignkey")
    op.drop_column("items", "user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        "items_user_id_fkey",
        "items",
        "users",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
