"""zz

Revision ID: d81903c49930
Revises: 99767f0ae0c5
Create Date: 2020-06-20 17:44:30.202685

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d81903c49930"
down_revision = "99767f0ae0c5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lots", sa.Column("is_demand", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lots", "is_demand")
    # ### end Alembic commands ###
